### ISSUE TITLE
decide language : Typescript or ES6?

### ISSUE THREAD

**Issue by rjatin007** [pesto-students/team-6#9]

**Comment by rjatin007** [comment]
@ArfatSalman

**Comment by ArfatSalman** [comment]
Using TS right now is not a good idea. It'll affect the speed right now. It's best to stick to JS as we are trying to learn about JS, React and Node. 

Maybe we can use them in some other projects. :)

**Comment by SangeethaKannas** [comment]
Thanks @ArfatSalman  We will continue with Javascript.
